### PR TITLE
fix: use the VSCode-provided ESTK instead of the installed version

### PR DESCRIPTION
**Pull request by sammarks**
It looks like ESTK is no longer supported starting with Catalina, but they have a VSCode extension that includes some bundled binaries that handle converting JSXBin code.

Since those are not available publicly on any package registry, it looks like the best option for now is to just include them in the repository, and hopefully Adobe will open-source those at some point in the future.

Makes the integration a little cleaner though!

(Sorry for all the file spam with the included resources, but they're necessary for it to work on all platforms).

### CODE REVIEW

**Comment by runegan** [comment]
This is really cool!
Tested it on my mac and works really well, and is also super fast!

Have you tested this on windows as well?

If so I'll merge into the repo and publish to npm

Thanks!

**Comment by sammarks** [comment]
Just tested on Windows. Had to download the extension there as well to make sure the proper file permissions were put in place (appears they were incorrect when downloading on Mac).

Ran the test suite with `npm test` and all were passing!

I _think_ this also means we can now use `jsxbin` in CI to automatically build and deploy any CEP extension / ExtendScript scripts.

**Comment by runegan** [comment]
Cool! I'll merge it and publish to npm then!

I was thinking about if CI was possible now as well, seems interesting and probably possible now. 

BTW: could you give some info on where you got the esdebugger code, I would like to add that to the readme.

Thank you!

**Comment by sammarks** [comment]
Yessir - I just installed the VSCode extension on my machine and trawled through the code to find what they were using in their script to batch compile jsxbin files.

There's a package it references that has all of this code in it, but it looks like it's hosted on a private package registry rather than npm, which is unfortunate.

**Pull request merged**
